# Correct pickle timestamps

## Imports

In [1]:
from pathlib import Path
import re
import logging

import numpy as np
import pandas as pd
import pingouin
import matplotlib.pyplot as plt
from matplotlib.colors import CenteredNorm, Normalize
from matplotlib.cm import ScalarMappable

from gulp2p.preproc.tiff import Tiff
from gulp2p.preproc.experiment import Experiment, create_expt_df
from gulp2p.preproc import utils, imaging, behavior, trial as tr
from gulp2p.viz import plotting

from matplotlib import rcParams
rcParams['pdf.fonttype'] = 42
rcParams['svg.fonttype'] = "none"

### Logging config

In [2]:
log_level = logging.INFO    # log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_format = "{asctime} - {levelname} - {name} - [{filename} {funcName}() {lineno}] - {message}"
logging.basicConfig(format=log_format, level=log_level, style="{") 

logging.getLogger("gulp2p").setLevel(logging.DEBUG)
logger = logging.getLogger(__name__)

## Select Data

### Functions:

In [3]:
CELL_TYPES = ["DR015", "DR018", "DR019"]

GENETIC_TOOLS = ["iGluSnFR"]

### Create trial dataframe:

In [4]:
TIFF_FOLDER = Path(r"Z:\2PImaging\Kerstin\MIMS")

trial_df = tr.create_trial_df(TIFF_FOLDER, CELL_TYPES, GENETIC_TOOLS)

In [5]:
trial_df.head()

,path,date,line,cell_type,genetic_tool,fly,trial
0,Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,1
1,Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,2
2,Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,3
3,Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,4
4,Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,1

### Sort into experiments:

In [6]:
expt_df = create_expt_df(trial_df, CELL_TYPES, GENETIC_TOOLS)

2024-07-24 12:18:06,086 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_iGluSnFRxSS2232_00001.tif
2024-07-24 12:18:06,094 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_iGluSnFRxSS2232_00002.tif
2024-07-24 12:18:06,104 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_iGluSnFRxSS2232_00003.tif
2024-07-24 12:18:06,106 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_iGluSnFRxSS2232_00004.tif
2024-07-24 12:18:06,122 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days_iGluSnFRxSS2232_Stripe_00001.tif
2024-07-24 12:18:06,129 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00001.tif
2024-07-24 12:18:06,138 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00002.tif
2024-07-24 12:18:06,145 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00003.tif
2024-07-24 12:18:06,148 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00004.tif
2024-07-24 12:18:06,157 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00005.tif
2024-07-24 12:18:06,167 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00006.tif
2024-07-24 12:18:06,167 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00007.tif
2024-07-24 12:18:06,177 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxDR015_00008.tif
2024-07-24 12:18:06,187 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00001.tif
2024-07-24 12:18:06,195 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00002.tif
2024-07-24 12:18:06,202 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00003.tif
2024-07-24 12:18:06,207 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00004.tif
2024-07-24 12:18:06,217 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00005.tif
2024-07-24 12:18:06,225 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231122\file_00006.tif
2024-07-24 12:18:06,225 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_00002.tif
2024-07-24 12:18:06,257 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_00003.tif
2024-07-24 12:18:06,257 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_00004.tif
2024-07-24 12:18:06,265 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_00005.tif
2024-07-24 12:18:06,275 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_00006.tif
2024-07-24 12:18:06,275 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_35pow_00001.tif
2024-07-24 12:18:06,275 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_35pow_00002.tif
2024-07-24 12:18:06,291 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly1_35pow_00003.tif
2024-07-24 12:18:06,291 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly3_00001.tif
2024-07-24 12:18:06,307 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly3_00002.tif
2024-07-24 12:18:06,307 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231128\20231128_DR019xiGluSnFr_Fly3_00003.tif
2024-07-24 12:18:06,322 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00001.tif
2024-07-24 12:18:06,322 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00002.tif
2024-07-24 12:18:06,338 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00003.tif
2024-07-24 12:18:06,338 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00004.tif
2024-07-24 12:18:06,338 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00005.tif
2024-07-24 12:18:06,353 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00006.tif
2024-07-24 12:18:06,353 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_00007.tif
2024-07-24 12:18:06,369 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_test_00001.tif
2024-07-24 12:18:06,376 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly1_test_00002.tif
2024-07-24 12:18:06,376 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00001.tif
2024-07-24 12:18:06,391 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00002.tif
2024-07-24 12:18:06,391 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00003.tif
2024-07-24 12:18:06,391 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00004.tif
2024-07-24 12:18:06,407 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00005.tif
2024-07-24 12:18:06,407 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231129\20231129_DR018xiGluSnFr_Fly2_00006.tif
2024-07-24 12:18:06,438 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly1_00001.tif
2024-07-24 12:18:06,438 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly1_00002.tif
2024-07-24 12:18:06,453 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly1_00003.tif
2024-07-24 12:18:06,454 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly1_00004.tif
2024-07-24 12:18:06,454 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly1_00005.tif
2024-07-24 12:18:06,469 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly2_00002.tif
2024-07-24 12:18:06,476 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly2_00003.tif
2024-07-24 12:18:06,476 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly3_00001.tif
2024-07-24 12:18:06,491 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly3_00002.tif
2024-07-24 12:18:06,491 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly3_00003.tif
2024-07-24 12:18:06,491 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231204\20231204_DR019xEF024_Fly3_00004.tif
2024-07-24 12:18:07,879 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231206\20231206_DR018xiGluSnFr_Fly2_00002.tif
2024-07-24 12:18:07,879 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231206\20231206_DR018xiGluSnFr_Fly2_00003.tif
2024-07-24 12:18:07,879 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231206\20231206_DR018xiGluSnFr_Fly2_00004.tif
2024-07-24 12:18:10,383 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231212\20231212_DR018xiGluSnFr_Fly2_00001.tif
2024-07-24 12:18:10,715 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00001.tif
2024-07-24 12:18:10,730 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00002.tif
2024-07-24 12:18:10,730 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00003.tif
2024-07-24 12:18:10,746 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00004.tif
2024-07-24 12:18:10,746 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00005.tif
2024-07-24 12:18:10,762 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly1_00006.tif
2024-07-24 12:18:11,055 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly2_00004.tif
2024-07-24 12:18:11,162 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20231214\20231214_DR015xiGluSnFr_Fly2_00006.tif
2024-07-24 12:18:12,117 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly1_00002.tif
2024-07-24 12:18:12,117 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly1_00003.tif
2024-07-24 12:18:12,233 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly1_00005.tif
2024-07-24 12:18:12,233 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly1_00006.tif
2024-07-24 12:18:12,233 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly1_00007.tif
2024-07-24 12:18:12,902 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240117\20240117_DR019xiGluSnFr_Fly2_00005.tif
2024-07-24 12:18:12,918 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240118\20240118_DR015xiGluSnFr_Fly1_00001.tif
2024-07-24 12:18:12,918 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240118\20240118_DR015xiGluSnFr_Fly1_00004.tif
2024-07-24 12:18:13,867 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240125\20240125_DR019xiGluSnFR_Fly02_00002.tif
2024-07-24 12:18:14,537 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240125\test_20240125_DR019xiGluSnFR_Fly01_00001.tif
2024-07-24 12:18:15,823 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240208\20240208_DR018xiGluSnFR_Fly01_00001.tif
2024-07-24 12:18:15,839 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240208\20240208_DR018xiGluSnFR_Fly01_00002.tif
2024-07-24 12:18:15,839 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240209\DR019xiGluSnFR_Fly01_00001.tif
2024-07-24 12:18:15,855 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240212\20240212_DR018xiGluSnFR_Fly01_00001.tif
2024-07-24 12:18:16,293 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00001.tif
2024-07-24 12:18:16,310 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00002.tif
2024-07-24 12:18:16,310 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00003.tif
2024-07-24 12:18:16,324 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00004.tif
2024-07-24 12:18:16,441 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00006.tif
2024-07-24 12:18:16,445 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00007.tif
2024-07-24 12:18:16,445 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240215\20240215_DR018xiGluSnFR_Fly01_00009.tif
2024-07-24 12:18:16,909 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240618\20240618_DR015xiGluSNfR_fly1_00001.tif
2024-07-24 12:18:17,042 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240618\20240618_DR015xiGluSNfR_fly1_00003.tif
2024-07-24 12:18:17,693 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240620\20240620_DRo15xiGluSnFR_fly2_00002.tif
2024-07-24 12:18:17,877 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240620\20240620_DRo15xiGluSnFR_fly2_00005.tif
2024-07-24 12:18:18,412 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly1_00001.tif
2024-07-24 12:18:18,428 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly1_00002.tif
2024-07-24 12:18:18,428 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly1_00003.tif
2024-07-24 12:18:18,445 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly1_00004.tif
2024-07-24 12:18:18,447 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly2_00001.tif
2024-07-24 12:18:18,447 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly2_00002.tif
2024-07-24 12:18:18,465 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly2_00003.tif
2024-07-24 12:18:18,471 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly2_00004.tif
2024-07-24 12:18:18,496 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240626\20240626_DR015xiGluSnfR_fly2_00005.tif
2024-07-24 12:18:18,558 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240702\20240702_DR015xiGluSnfR_fly1_00001.tif
2024-07-24 12:18:19,028 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240702\20240702_DR015xiGluSnfR_fly1_00008.tif
2024-07-24 12:18:19,962 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGluSnfR_fly1_00002.tif
2024-07-24 12:18:19,962 - INFO - gulp2p.preproc.utils - [utils.py load_trial() 639] - trial not processed: Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGluSnfR_fly1_00003.tif

In [7]:
expt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   expt_name         40 non-null     object
 1   trial_paths       40 non-null     object
 2   date              40 non-null     object
 3   line              39 non-null     object
 4   cell_type         39 non-null     object
 5   genetic_tool      39 non-null     object
 6   fly               40 non-null     int64
 7   trials            40 non-null     object
 8   proc_trial_count  40 non-null     int64
dtypes: int64(2), object(7)
memory usage: 2.9+ KB

In [8]:
expt_df.tail()

,expt_name,trial_paths,date,line,cell_type,genetic_tool,fly,trials,proc_trial_count
35,20240626_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240626\20240626_D...,20240626,DR015xiGluSnfR,DR015,iGluSnFR,1,[],0
36,20240626_DR015xiGluSnfR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240626\20240626_D...,20240626,DR015xiGluSnfR,DR015,iGluSnFR,2,[],0
37,20240702_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240702\20240702_D...,20240702,DR015xiGluSnfR,DR015,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,14
38,20240708_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGlu...,20240708,DR015xiGluSnfR,DR015,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,1
39,20240708_DR015xiGluSnfR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGlu...,20240708,DR015xiGluSnfR,DR015,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,5

In [9]:
expt_df

,expt_name,trial_paths,date,line,cell_type,genetic_tool,fly,trials,proc_trial_count
0,20231109_iGluSnFRxSS2232_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231109\Fly1_8days...,20231109,iGluSnFRxSS2232,iGluSnFR,SS2232,1,[],0
1,20231121_iGluSnFRxDR015_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231121\iGluSnFRxD...,20231121,iGluSnFRxDR015,iGluSnFR,DR015,1,[],0
2,20231122_None_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231122\file_00001...,20231122,None,None,None,1,[],0
3,20231128_DR019xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231128\20231128_D...,20231128,DR019xiGluSnFr,DR019,iGluSnFR,1,[],0
4,20231128_DR019xiGluSnFr_Fly3,[Z:\2PImaging\Kerstin\MIMS\20231128\20231128_D...,20231128,DR019xiGluSnFr,DR019,iGluSnFR,3,[],0
5,20231129_DR018xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231129\20231129_D...,20231129,DR018xiGluSnFr,DR018,iGluSnFR,1,[],0
6,20231129_DR018xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231129\20231129_D...,20231129,DR018xiGluSnFr,DR018,iGluSnFR,2,[],0
7,20231204_DR019xEF024_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231204\20231204_D...,20231204,DR019xEF024,DR019,EF024,1,[],0
8,20231204_DR019xEF024_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231204\20231204_D...,20231204,DR019xEF024,DR019,EF024,2,[],0
9,20231204_DR019xEF024_Fly3,[Z:\2PImaging\Kerstin\MIMS\20231204\20231204_D...,20231204,DR019xEF024,DR019,EF024,3,[],0
10,20231206_DR018xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231206\20231206_D...,20231206,DR018xiGluSnFr,DR018,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,10
11,20231206_DR018xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231206\20231206_D...,20231206,DR018xiGluSnFr,DR018,iGluSnFR,2,[],0
12,20231207_DR019xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231207\20231207_D...,20231207,DR019xiGluSnFr,DR019,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,9
13,20231207_DR019xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231207\20231207_D...,20231207,DR019xiGluSnFr,DR019,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,3
14,20231212_DR018xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231212\20231212_D...,20231212,DR018xiGluSnFr,DR018,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,11
15,20231212_DR018xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231212\20231212_D...,20231212,DR018xiGluSnFr,DR018,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,3
16,20231214_DR015xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231214\20231214_D...,20231214,DR015xiGluSnFr,DR015,iGluSnFR,1,[],0
17,20231214_DR015xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20231214\20231214_D...,20231214,DR015xiGluSnFr,DR015,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,5
18,20231219_DR019xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20231219\20231219_D...,20231219,DR019xiGluSnFr,DR019,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,6
19,20240116_DR018xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240116\20240116_D...,20240116,DR018xiGluSnFr,DR018,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,1
20,20240117_DR019xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240117\20240117_D...,20240117,DR019xiGluSnFr,DR019,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,6
21,20240117_DR019xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240117\20240117_D...,20240117,DR019xiGluSnFr,DR019,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,3
22,20240118_DR015xiGluSnFr_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240118\20240118_D...,20240118,DR015xiGluSnFr,DR015,iGluSnFR,1,[],0
23,20240118_DR015xiGluSnFr_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240118\20240118_D...,20240118,DR015xiGluSnFr,DR015,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,5
24,20240124_DR019xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240124\20240124_D...,20240124,DR019xiGluSnFR,DR019,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,6
25,20240125_DR019xiGluSnFR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240125\20240125_D...,20240125,DR019xiGluSnFR,DR019,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,9
26,20240125_DR019xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240125\test_20240...,20240125,DR019xiGluSnFR,DR019,iGluSnFR,1,[],0
27,20240129_DR19xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240129\20240129_D...,20240129,DR19xiGluSnFR,DR019,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,12
28,20240208_DR018xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240208\20240208_D...,20240208,DR018xiGluSnFR,DR018,iGluSnFR,1,[],0
29,20240209_DR019xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240209\DR019xiGlu...,20240209,DR019xiGluSnFR,DR019,iGluSnFR,1,[],0
30,20240212_DR018xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240212\20240212_D...,20240212,DR018xiGluSnFR,DR018,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,5
31,20240215_DR018xiGluSnFR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240215\20240215_D...,20240215,DR018xiGluSnFR,DR018,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,1
32,20240215_DR018xiGluSnFR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240215\20240215_D...,20240215,DR018xiGluSnFR,DR018,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,6
33,20240618_DR015xiGluSNfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240618\20240618_D...,20240618,DR015xiGluSNfR,DR015,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,7
34,20240620_DRo15xiGluSnFR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240620\20240620_D...,20240620,DRo15xiGluSnFR,DR015,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,8
35,20240626_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240626\20240626_D...,20240626,DR015xiGluSnfR,DR015,iGluSnFR,1,[],0
36,20240626_DR015xiGluSnfR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240626\20240626_D...,20240626,DR015xiGluSnfR,DR015,iGluSnFR,2,[],0
37,20240702_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240702\20240702_D...,20240702,DR015xiGluSnfR,DR015,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,14
38,20240708_DR015xiGluSnfR_Fly1,[Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGlu...,20240708,DR015xiGluSnfR,DR015,iGluSnFR,1,[<gulp2p.preproc.trial.Trial object at 0x00000...,1
39,20240708_DR015xiGluSnfR_Fly2,[Z:\2PImaging\Kerstin\MIMS\20240708\DR015xiGlu...,20240708,DR015xiGluSnfR,DR015,iGluSnFR,2,[<gulp2p.preproc.trial.Trial object at 0x00000...,5

## Correct timestamps

In [16]:
# For each trial:
#   get pickle name without timestamp prepended
#   Search for pickle files that contain the name
#       There should only be one
#   Rename the file with the new timestamp

for index, expt_df_row in expt_df.iterrows():
    
    for trial_path in expt_df_row['trial_paths']:
        tiff = Tiff(trial_path)
        pickle_path = utils.get_trial_pickle_path(trial_path, tiff.metadata['date'])

        pickle_date = pickle_path.name.split('-')[0]
        pickle_name_timestampless = '_'.join(pickle_path.name.split('_')[1:])
        search_key = f"{pickle_date}*{pickle_name_timestampless}"
        matching_pickles = list(pickle_path.parent.glob(search_key))

        if len(matching_pickles) == 0:
            # print(f"no pickle matches: {pickle_path}")
            continue

        if len(matching_pickles) != 1:
            # print(f"too many pickle matches: {pickle_path}")
            print(matching_pickles)
            continue

        if pickle_path == matching_pickles[0]:
            # print(f"pickle name matches: {pickle_path}")
            continue

        # Rename pickle file
        print(f"renaming {matching_pickles[0]} to {pickle_path}")
        matching_pickles[0].rename(pickle_path)

renaming Z:\GULP\Data\pickle\preproc\2024_07\20240708-124011_DR015xiGluSnfR_fly1_00002.pickle to Z:\GULP\Data\pickle\preproc\2024_07\20240708-104642_DR015xiGluSnfR_fly1_00002.pickle
renaming Z:\GULP\Data\pickle\preproc\2024_07\20240708-124023_DR015xiGluSnfR_fly1_00003.pickle to Z:\GULP\Data\pickle\preproc\2024_07\20240708-105612_DR015xiGluSnfR_fly1_00003.pickle